<?php

namespace AppBundle\Repository;

/**
 * DiscographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscographieRepository extends \Doctrine\ORM\EntityRepository
{
}
