<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPseudoAuteurCommencePar()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM AppBundle:Article a ORDER BY a.titre ASC');
        return $query->getResult();
    }

    public function findPseudoAuteurCommencePar2()
    {
      $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('a')
                    ->orderBy('a.pseudo','ASC')
                    ->getQuery();
        return $query->getResult();

    }


    public function findPseudoAuteurCommencePar3($recherche)
    {
      $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT a FROM AppBundle:Article a JOIN a.auteur u WHERE u.pseudo LIKE ''%:recherche%'")
                    ->setParameter('recherche', $recherche);
        return $query->getResult();

    }


    public function findAllArticle()
    {
      $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT COUNT(a.id) FROM AppBundle:Article a");

        return $query->getSingleScalarResult();

    }

}
