<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllUtilisateur()
  {
    $em = $this->getEntityManager();
      $query = $em->createQuery("SELECT COUNT(u.id) FROM AppBundle:Utilisateur u");

      return $query->getSingleScalarResult();

  }

}
